#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../terraform/environments/lab"
INVENTORY_DIR="$SCRIPT_DIR/../provisioning/ansible/inventory"
OUT_FILE="$INVENTORY_DIR/terraform.lab.ini"
KEY_FILE="${ISUCON_SSH_KEY:-$HOME/.ssh/splunk_aws_key.pem}"

cd "$TERRAFORM_DIR"

APP_IPS=$(terraform output -json app_public_ips)
DB_IP=$(terraform output -raw db_public_ip)
BENCH_IP=$(terraform output -raw bench_public_ip)

mkdir -p "$INVENTORY_DIR"

cat > "$OUT_FILE" <<EOF
# Generated by scripts/03-generate-ansible-inventory.sh
# Do not edit manually.

[application]
EOF

echo "$APP_IPS" | jq -r '.[]' >> "$OUT_FILE"

cat >> "$OUT_FILE" <<EOF

[db]
$DB_IP

[benchmarker]
$BENCH_IP

[application:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=$KEY_FILE

[db:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=$KEY_FILE

[benchmarker:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=$KEY_FILE
EOF

echo "Wrote $OUT_FILE"
cat "$OUT_FILE"
